// import LinkedIn from "../assets/images/icons/linkedinClone.jpg";
import LinkedIn from "../assets/images/icons/linkedin.png";
import NodeJWT from "../assets/images/icons/jwtnode.png";
import Covid19 from "../assets/images/icons/covid3.png";
import VideoPlayer from "../assets/images/icons/videoplayer.png";
import ReactApp from "../assets/images/icons/reactapp.png";
import Tinder from "../assets/images/icons/tinderClone.png";

export const Cards = [
	{
		id: "a5b721fd-d5fa-4c07-909f-4515c8c4891c",
		target: "_blank",
		linkToProject: "https://linkedin-clone-345ed.web.app/",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: LinkedIn,
		cardTitle: "linkedin clone",
		cardDescription: "ReactJS - Redux - Firebase - ReactFlipMove",
	},
	{
		id: "4e076153-d5a5-44df-9c3d-e516cc781aae",
		target: "_blank",
		linkToProject: "https://github.com/Petrit-Halabaku/jwt-node",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: NodeJWT,
		cardTitle: "jwt - node.js",
		cardDescription: "NodeJS implementation of jwt tokens",
	},
	{
		id: "6484770f-e5c0-4ff9-8f5c-9933fc760616",
		target: "_blank",
		linkToProject: "https://covid-pandemy.herokuapp.com/",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: Covid19,
		cardTitle: "COVID - 19 tracker",
		cardDescription: "ReactJS - MaterialUI - chartJS",
	},
	{
		id: "933ff6df-49ba-492d-b229-dbfc28c216ac",
		target: "_blank",
		linkToProject: "https://github.com/Petrit-Halabaku/video-player-w-hooks",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: VideoPlayer,
		cardTitle: "Video Player w/React",
		cardDescription: "Hooks - ReactJS - Styled Components - reactPlayer",
	},
	{
		id: "5173f508-dfc8-4720-9cf5-cb83ac027b90",
		target: "_blank",
		linkToProject: "https://github.com/Petrit-Halabaku/react-project",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: ReactApp,
		cardTitle: "Intro React Project",
		cardDescription: "Elemetary ReactJS app",
	},
	{
		id: "526ccb7f-5866-4d6e-9230-780842b4a98d",
		target: "_blank",
		linkToProject: "https://github.com/Petrit-Halabaku/tinder-clone",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: Tinder,
		cardTitle: "tinder clone",
		cardDescription: "This is a clone of Tinder using ReactJS",
	},
	{
		id: "d0a50193-4d83-42d6-951d-93b8bf149961",
		target: "_blank",
		linkToProject: "https://linkedin-clone-345ed.web.app/",
		roundedBorder: true,
		status: "portfolio",
		overlayImage: true,
		fullHeight: true,
		show: true,
		portfolio: true,
		type: "object",
		cardImage: LinkedIn,
		cardTitle: "linkedin clone",
		cardDescription: "ReactJS - Redux - Firebase - reactFlipMove",
	},
];
